<!DOCTYPE html>
<html>
    <head>
        <title><?php echo(self::$_title); ?></title>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="robots" content="<?php echo(self::$_robots); ?>" />

        <link href="/frontend/css/style.css" rel="stylesheet" media="screen" />
    </head>
    <body>
        <div id="container">
            <h1>Добро пожаловать!</h1>

            <div id="body">
                <?php
                $this->_executeAction('body');
                ?>
            </div>

            <p id="footer">
                <?php
                $this->_executeAction('todayDate');
                ?>
            </p>
        </div>
    </body>
</html>