<!DOCTYPE html>
<html>
    <head>
        <title>Ошибка</title>

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="robots" content="none" />

        <style type="text/css">
            body {
                background-color: #fff;
                color: #4F5155;
                font: 13px/20px normal Helvetica, Arial, sans-serif;
                margin: 40px;
            }

            #container {
                border: 1px solid #D0D0D0;
                margin: 10px;
            }

            h1 {
                background-color: transparent;
                border-bottom: 1px solid #D0D0D0;
                color: #444;
                font-size: 19px;
                font-weight: normal;
                margin: 0 0 14px 0;
                padding: 14px 15px 10px 15px;
            }

            p {
                margin: 12px 15px 12px 15px;
            }
        </style>
    </head>
    <body>
        <?php
        if (isset($message)) {
            ?>
            <div id="container">
                <h1>Ошибка</h1>
                <p><?php echo($message); ?></p>
            </div>
            <?php
        }
        ?>
    </body>
</html>